### ISSUE TITLE
What I need to install on my centos for exec the exe to read from my cache on window?

### ISSUE THREAD

**Issue by 1009058470** [intersystems/quickstarts-dotnet#2]
I have 2 machine, 1 is windows ,another is centos, 
I install cache on windows and i have a exe is running on centos, **what i need is the exe running on centos needed read from windows cache** 
how i can do?

**Comment by eduard93** [comment]
Please use:

- [WRC](https://wrc.intersystems.com/wrc/)
- [Developers Community](https://community.intersystems.com/)

To ask questions about the use of InterSystems technology.

Issues are for a more specific bugs/feature requests/etc.
